//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVTWebapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABONE_BILGI
    {
        public long Id { get; set; }
        public Nullable<decimal> BOLGE_KODU { get; set; }
        public string BOLGE_ADI { get; set; }
        public Nullable<decimal> KARNE_NO { get; set; }
        public string KARNE_ADRESI { get; set; }
        public Nullable<decimal> TESISAT_NO { get; set; }
        public string MARKA { get; set; }
        public string SAYAC_MARKA_ADI { get; set; }
        public Nullable<decimal> SAYAC_NO { get; set; }
        public string UNVAN { get; set; }
        public string ADRES { get; set; }
        public Nullable<decimal> SOZLESME_TARIHI { get; set; }
        public Nullable<decimal> IPTAL_TARIHI { get; set; }
        public string SOZLESME_UNVANI { get; set; }
        public string AKTARIM_ZAMANI { get; set; }
        public string IL_KODU { get; set; }
    }
}
