//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVTWebapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Districts
    {
        public string districtCode { get; set; }
        public string districtName { get; set; }
    }
}
