//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVTWebapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uavt_63
    {
        public string IL { get; set; }
        public string ILCE_KODU { get; set; }
        public string ILCE_ADI { get; set; }
        public string BUCAK_KODU { get; set; }
        public string BUCAK_ADI { get; set; }
        public string KOY_KODU { get; set; }
        public string KOY_ADI { get; set; }
        public string MAHALLE_KODU { get; set; }
        public string MAHALLE_ADI { get; set; }
        public string CSBM_KODU { get; set; }
        public string CSBM_ADI { get; set; }
        public string BINA_KODU { get; set; }
        public string DIS_KAPI_NO { get; set; }
        public string SITE_ADI { get; set; }
        public string BLOK_ADI { get; set; }
        public string UAVT_ADRES_NO { get; set; }
        public string IC_KAPI_NO { get; set; }
    }
}
