//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVTWebapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uavts
    {
        public decimal serno { get; set; }
        public Nullable<int> checkStatus { get; set; }
        public Nullable<decimal> createDate { get; set; }
        public string customerName { get; set; }
        public string districtCode { get; set; }
        public string doorNumber { get; set; }
        public Nullable<int> existOnUavt { get; set; }
        public string meterBrand { get; set; }
        public string meterNo { get; set; }
        public string uavtCode { get; set; }
        public Nullable<decimal> userSerno { get; set; }
        public string wiringNo { get; set; }
        public string villageCode { get; set; }
        public string streetCode { get; set; }
        public string csbmCode { get; set; }
        public string indoorNumber { get; set; }
        public Nullable<decimal> processDate { get; set; }
        public string siteName { get; set; }
        public string blockName { get; set; }
        public string meterBrandCode { get; set; }
    }
}
