//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVTWebapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSyncHistories
    {
        public decimal serno { get; set; }
        public Nullable<decimal> districtCode { get; set; }
        public Nullable<decimal> lastMbsSyncDate { get; set; }
        public Nullable<decimal> lastUavtSyncDate { get; set; }
        public Nullable<decimal> userSerno { get; set; }
    }
}
