//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVTWebapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Villages
    {
        public int Id { get; set; }
        public string CITY_CODE { get; set; }
        public string COUNTY_CODE { get; set; }
        public string COUNTY_NAME { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string VILLAGE_CODE { get; set; }
        public string VILLAGE_NAME { get; set; }
    }
}
